---
abstract: 'This distribution aids in the creation of BioMOBY perl based web services.'
build_requires:
  ExtUtils::MakeMaker: 6.11
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.67'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MOSES-MOBY
no_index:
  directory:
    - bin/scripts
    - inc
    - t
requires:
  Carp: 0
  Config::Simple: 4.58
  File::HomeDir: 0.65
  File::ShareDir: 0.05
  File::Spec: 0.80
  IO::Stringy: 2.11
  Log::Log4perl: 1.12
  SOAP::Lite: 0.69
  Template: 1.11
  Unicode::String: 2.09
  XML::LibXML: 1.62
  IO::Template: .99
  Want: 0
  version: 0
version: 0.82
